---
title: "Plot All Storms"
author: "Steve Walsh"
date: "1/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sp)
library(raster)
library(ncdf4)
library(sf)
library(dplyr)
library(stringr) #str_locate_all "_218_" in the NAM file names

# install.packages("rgdal", type = "source", configure.args="--with-gdal-config=/Library/Frameworks/GDAL.framework/unix/bin/gdal-config --with-proj-include=/Library/Frameworks/PROJ.framework/unix/include --with-proj-lib=/Library/Frameworks/PROJ.framework/unix/lib --with-proj-share=/Library/Frameworks/PROJ.framework/unix/share/proj --with-proj-data=/Library/Frameworks/PROJ.framework/unix/share/proj --with-data-copy=yes")
```

```{r grib2netcdf, eval=F, include=F}
#netcdf product is bad
all.grb.folders <- list.dirs("/Volumes/LACIEHD/NAMandST4", recursive = F)
for(i in 1:length(all.grb.folders)){
  print(i)
  currentST4_NAM_folders <- list.dirs(all.grb.folders[i],full.names = F)[-1]
  ST4_folder <- currentST4_NAM_folders[1]
  NAM_folder <- currentST4_NAM_folders[2]
  fullpathST4_NAM_folders <- list.dirs(all.grb.folders[i],full.names = T)[-1]
  ST4_folder_full <- fullpathST4_NAM_folders[1]
  NAM_folder_full <- fullpathST4_NAM_folders[2]
  
  dir.create(paste(gsub("GRB_NAMandST4","GRB.to.NCDF",all.grb.folders[i])))
  dir.create(paste(gsub("GRB_NAMandST4","GRB.to.NCDF",all.grb.folders[i]),"/",NAM_folder,sep = ""))
  dir.create(paste(gsub("GRB_NAMandST4","GRB.to.NCDF",all.grb.folders[i]),"/",ST4_folder,sep = ""))
  
  print(length(list.files(NAM_folder_full)))
  print(list.files(NAM_folder_full))

  for (NAMfile in list.files(NAM_folder_full)) {
    r <- suppressMessages(raster(paste(NAM_folder_full,"/",NAMfile,sep = "")))
    n <- writeRaster(r, filename = paste(gsub("GRB_NAMandST4","GRB.to.NCDF",all.grb.folders[i]),"/",NAM_folder,
                                         "/",gsub(".grb2",".nc",gsub(".grib",".nc",NAMfile)),sep = ""), format = "CDF")#, overwrite = TRUE)
  }
  
  for (ST4file in list.files(ST4_folder_full)) {
    s <- raster(paste(ST4_folder_full,"/",ST4file,sep = ""))
    m <- writeRaster(s, filename = paste(gsub("GRB_NAMandST4","GRB.to.NCDF",all.grb.folders[i]),"/",ST4_folder,
                                         "/",gsub(".06h",".nc",ST4file),sep = ""), format = "CDF")#, overwrite = TRUE)
  }
}
```
```{r read.netcdf, eval=F, include=F}
#netcdf product is bas
n
m
ncin <- nc_open(paste(gsub("GRB_NAMandST4","GRB.to.NCDF",all.grb.folders[i]),"/",ST4_folder,
                                         "/",gsub(".06h",".nc",ST4file),sep = ""))
ncvar_get(nc = ncin)
names(ncin$var)
plot(v)
print(ncin)
str(ncin)
plot(ncin$var)
```
```{r regrid,      eval=F, include=F}
#this is good
rast4 <- raster("/Volumes/LACIEHD/ST4/2005katrina2/ST4.2005082918.06h")
rast5 <- raster("/Volumes/LACIEHD/ST4/2005katrina2/ST4.2005083000.06h")
rast6 <- rast4 + rast5
projected_raster <- projectRaster(rast6, crs = "+proj=longlat +datum=WGS84")

plot(projectRaster(rast4, crs = "+proj=longlat +datum=WGS84")); plot(st_geometry(spData::us_states), add=TRUE)
plot(projectRaster(rast5, crs = "+proj=longlat +datum=WGS84")); plot(st_geometry(spData::us_states), add=TRUE)

nam1 <- raster("/Volumes/LACIEHD/NAMhurtrial/nam_218_20050829_1200_f012.grib copy", band=10)
nam2 <- raster("/Volumes/LACIEHD/NAMhurtrial/nam_218_20050829_1200_f012.grib copy", band=11)

plot(projectRaster(nam1, crs = "+proj=longlat +datum=WGS84")); plot(st_geometry(spData::us_states), add=TRUE)
plot(projectRaster(nam2, crs = "+proj=longlat +datum=WGS84")); plot(st_geometry(spData::us_states), add=TRUE)
# library(rgdal)
# gribdata = readGDAL("/Volumes/LACIEHD/NAMhurtrial/nam_218_20050829_1200_f012.grib copy") 
# gribdata@bbox
# install.packages("GrADS")
# been <- GDALinfo("/Volumes/LACIEHD/NAMhurtrial/nam_218_20050829_1200_f012.grib copy")
#need wgrib2 installed, c compiler issues; see bovine aerospace website rNOMADS::ReadGrib("/Volumes/LACIEHD/NAMhurtrial/nam_218_20050829_1200_f012.grib copy")

projected_nam <- projectRaster(nam1, crs = "+proj=longlat +datum=WGS84")
regrid_st4<-resample(projected_raster,projected_nam)
error <- projected_nam-regrid_st4
plot(error, breaks=seq(-90,90,10),  xlim=c(-110,-55), ylim=c(23,50),col=colorspace::diverge_hsv(18))
plot(st_geometry(spData::us_states), add=TRUE)
image(error, xlim=c(-110,-55), ylim=c(23,50),zlim=c(-100,100), col=colorspace::diverge_hsv(99))
plot(st_geometry(spData::us_states), add=TRUE)
library("latticeExtra")
spplot(error, col.regions= colorspace::diverge_hsv(131), at=seq(-100,101,2),
       sp.layout = "states_shp/states.shp")
#plot(projected_nam); plot(st_geometry(spData::us_states), add=TRUE)
```
```{r regrid.mask, eval=F, include=F}
#this is good
mask <- raster("lsmask.nc")
mask[mask==-1] <- 0
extent(mask)[1] <- extent(mask)[1]-360
extent(mask)[2] <- extent(mask)[2]-360

NAM15deg <- flip(flip(t(raster("/Volumes/WD PASSPORT/NC_NAMandST4trial/2012debby copy/nam_218_2012062500debby/nam_218_20120629_0000_024.nc")),direction='y'),direction = "x")

mask15deg <- resample(mask, NAM15deg, method='ngb')
plot(NAM15deg*mask15deg)
plot(st_geometry(spData::us_states),xlim=c(-100,-65), ylim=c(23,50), add=TRUE)
```
```{r plot.storms, eval=F, include=F}
#this is good
all.storm.folders <- list.dirs("/Volumes/LACIEHD/NAMandST4/", recursive = F)
for(i in 1:length(all.storm.folders)){
  i <- 1
  print(i)
  currentST4_NAM_folders <- list.dirs(all.storm.folders[i])[-1] #uncomment the [-1] when st4 and nam folders are together
  ST4_folder <- currentST4_NAM_folders[1]
  NAM_folder <- currentST4_NAM_folders[2] #uncomment this as well
  
  print(length(list.files(NAM_folder)))
  print(list.files(NAM_folder))
  
  for (NAMfile in list.files(NAM_folder)[1:3]) {
    NAMfile
    date_start <- str_locate_all(pattern ='_218_', NAMfile)[[1]][1,2] + 1
    storm_date <- as.numeric(substr(NAMfile,date_start,date_start+7))
    if(storm_date < 20060701){NAM_band <- 10} else if(storm_date > 20060701 && storm_date < 20170101){NAM_band <- 11} else {NAM_band <- 373}
    print(NAM_band)
    # masked_NAM <- flip(flip(t(raster(paste(NAM_folder,"/",NAMfile,sep=""))),direction='y'),direction = "x") * mask15deg
    # plot(masked_NAM,
    #      xlim=c(-100,-65), ylim=c(23,50), main=NAMfile)
    # plot(st_geometry(spData::us_states),xlim=c(-100,-65), ylim=c(23,50), add=TRUE)
    # 
    # nam_file12 <- "NAM HARVEY/nam_218_20170826_0000_012.grb2-var48-t0.nc"
    # nam_variable12 <- raster(nam_file12, varname=names(nc_open(nam_file12)$var))
  }
  
  # for (ST4file in list.files(ST4_folder)) {
  #   masked_ST4 <- flip(flip(t(raster(paste(ST4_folder,"/",ST4file,sep=""))),direction='y'),direction = "x") * mask15deg
  #   plot(masked_ST4,
  #        xlim=c(-100,-65), ylim=c(23,50), main=ST4file)
  #   plot(st_geometry(spData::us_states),xlim=c(-100,-65), ylim=c(23,50), add=TRUE)
  # }
}

#vector <- c(rep(NA,10))
```

Plotting all NAMs first 24 hours, except JPEG2000 driver issues

```{r plot.all.41}
all.storm.folders <- list.dirs("G:\\NAMandST4", recursive = F)
NAMlist <- list()
ST4list <- list()
mask <- raster("G:\\lsmask.nc")
mask[mask==-1] <- 0
extent(mask)[1] <- extent(mask)[1]-360
extent(mask)[2] <- extent(mask)[2]-360
mask.regrid <- resample(mask, projectRaster(raster("G:\\nam_218_20050829_1200_f012.grib"),crs = "+proj=longlat +datum=WGS84"), method='ngb')


for(i in 1:length(all.storm.folders)){
  # [-c(15:36)],[c(1:16,35:39)] right after all.storm.folders to use only the ones without jpeg2000 issue
  # i <- 1
  print(i)
  currentST4_NAM_folders <- list.dirs(all.storm.folders[i])[-1] #uncomment the [-1] when st4 and nam folders are together
  ST4_folder <- currentST4_NAM_folders[1]
  NAM_folder <- currentST4_NAM_folders[2] #uncomment the [2] as well
  
  print(length(list.files(NAM_folder)))
  #print(list.files(NAM_folder))
  NAMlist[[i]] <- list()
  ST4list[[i]] <- list()
  if(length(list.files(NAM_folder,full.names = T))==18){first24 <- c(7,8)} else 
  if(length(list.files(NAM_folder,full.names = T))==15){first24 <- c(5,6)} else {print("something went wrong"); next}
  for (j in 1:length(list.files(NAM_folder,full.names = T)[first24])) {
    # j <-1
    NAMfile <- list.files(NAM_folder,full.names = T)[j]
    # paste(NAM_folder,"/",NAMfile, sep = "") #don't need when full.names=T in list.dirs
    date_start <- str_locate_all(pattern ='_218_', NAMfile)[[1]][1,2] + 1
    storm_date <- as.numeric(substr(NAMfile,date_start,date_start+7))
    if(storm_date < 20060701){NAM_band <- 10} else if(storm_date > 20060701 && storm_date < 20170101){NAM_band <- 11} else {NAM_band <- 373}
    print(NAM_band)
    NAMlist[[i]][[j]] <- (raster(NAMfile, band=NAM_band) %>% projectRaster(crs = "+proj=longlat +datum=WGS84"))
    print(min(values(NAMlist[[i]][[j]]), na.rm=T))
    values(NAMlist[[i]][[j]])[which(values(NAMlist[[i]][[j]]<0))] <- 0 #change negative projected precipitation to 0
  }
  for (k in 1:length(list.files(ST4_folder,full.names = T)[1:4])) {
    # k <-1
    ST4file <- list.files(ST4_folder,full.names = T)[k]
    ST4list[[i]][[k]] <- (raster(ST4file) %>% projectRaster(crs = "+proj=longlat +datum=WGS84"))
    ST4list[[i]][[k]] <- resample(ST4list[[i]][[k]], mask.regrid, method = "bilinear")
    
    print(min(values(ST4list[[i]][[k]]), na.rm=T))
    values(ST4list[[i]][[k]])[which(values(ST4list[[i]][[k]]<0))] <- 0 #change negative projected precipitation to 0
  }
  first24NAM <- (NAMlist[[i]][[1]]+NAMlist[[i]][[2]])*mask.regrid
  first24ST4 <- (ST4list[[i]][[1]]+ST4list[[i]][[2]]+ST4list[[i]][[3]]+ST4list[[i]][[4]])*mask.regrid
  plot(first24NAM, xlim=c(-110,-55), ylim=c(23,50), main=paste(all.storm.folders[i],"NAM"));plot(st_geometry(spData::us_states), add=TRUE)
  plot(first24ST4, xlim=c(-110,-55), ylim=c(23,50), main=all.storm.folders[i]);plot(st_geometry(spData::us_states), add=TRUE)
  plot(first24NAM-first24ST4, breaks=seq(-300,300,30),  xlim=c(-110,-55), ylim=c(23,50),col=colorspace::diverge_hsv(20),
       main="Error, Forecast NAM - Observed ST4")
  plot(st_geometry(spData::us_states), add=TRUE)
  min(values(first24NAM-first24ST4),na.rm = T);max(values(first24NAM-first24ST4),na.rm = T)
}

```