---
title: "Plot All Storms"
author: "Steve Walsh"
date: "1/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sp)
library(raster)
library(ncdf4)
library(sf)
library(dplyr)
library(stringr) #str_locate_all "_218_" in the NAM file names
library(rgdal)
library(colorspace)
library(ggplot2)
# library(gridExtra)
# library(cowplot)
```

Plotting 44 Storms' Log Precipitation for First 24 Hours After Landfall

```{r plot.all.41}
pdf("logbuffer.2.28.19.pdf")
all.storm.folders <- list.dirs("NAMandST4", recursive = F) #/Volumes/LACIEHD/
most.storm.folders <- list.dirs("NAMandST4", recursive = F)[-1]#[-c(1,13:35)] #/Volumes/LACIEHD/
# these will be lists of lists (#lists=#storms), where each element in a list is rasters for a storm
NAMlist <- list()
ST4list <- list()

# load, modify and project land/sea mask 
mask <- raster("lsmask.nc")
mask[mask==-1] <- 0
extent(mask)[1] <- extent(mask)[1]-360
extent(mask)[2] <- extent(mask)[2]-360
mask.regrid <- resample(mask, projectRaster(raster("nam_218_20050829_1200_f012.grib"),
                                            crs = "+proj=longlat +datum=WGS84"), method='ngb') 

# Multiple plot function
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  #
  # ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
  # - cols:   Number of columns in layout
  # - layout: A matrix specifying the layout. If present, 'cols' is ignored.
  #
  # If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
  # then plot 1 will go in the upper left, 2 will go in the upper right, and
  # 3 will go all the way across the bottom.
  #
  library(grid)
  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)
  numPlots = length(plots)
  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }
 if (numPlots==1) {
    print(plots[[1]])
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

#Buffer function (two eye locations)
ST4bufferprecip <- function(NAM_df,LatLonVec,LatLonVec2,radius){
  centerLat <- as.numeric(LatLonVec[1])
  centerLon <- as.numeric(LatLonVec[2])
  centerLat2 <- as.numeric(LatLonVec2[1])
  centerLon2 <- as.numeric(LatLonVec2[2])
  
  # scale longtitude grid (since it's a fcn of latitude)
  lonscale = cos(abs(centerLat*pi/180));
  Ydist = (NAM_df[,2]-centerLat)*110.54; # convert to km [i,j]
  Xdist = (NAM_df[,1]-centerLon)*111.32*lonscale; #[i,j]
  radialdist = abs(sqrt(Ydist^2+Xdist^2));
  
  lonscale2 = cos(abs(centerLat2*pi/180));
  Ydist2 = (NAM_df[,2]-centerLat2)*110.54; # convert to km [i,j]
  Xdist2 = (NAM_df[,1]-centerLon2)*111.32*lonscale; #[i,j]
  radialdist2 = abs(sqrt(Ydist2^2+Xdist2^2));
  
  buffer_precip <- ifelse(radialdist < radius, NAM_df[,3], 0)
  buffer_precip2 <- ifelse(radialdist < radius|radialdist2<radius, buffer_precip, NA)
  
  ST4_df_buffer <- cbind(NAM_df[,1:2],buffer_precip2)
  raster_buffer <- rasterFromXYZ(ST4_df_buffer)
  return(raster_buffer)
}

for(i in 1:length(most.storm.folders)){
  # i <- 1
  print(i)
  currentST4_NAM_folders <- list.dirs(most.storm.folders[i])[-1] #uncomment the [-1] when st4 and nam folders are together
  ST4_folder <- currentST4_NAM_folders[1]
  NAM_folder <- currentST4_NAM_folders[2] #uncomment the [2] as well
  hurdat_csv <- list.files(most.storm.folders[i], pattern = ".csv")
  
  print(length(list.files(NAM_folder))) #should be 15 or 18, depending if 72hr timestep exists
  NAMlist[[i]] <- list()
  ST4list[[i]] <- list()
  
  #Identifying where in the NAM folder the first 24 hours after landfall files are (latest timestep)
  if(length(list.files(NAM_folder,full.names = T))==18){first24 <- c(7,8)} else {
    if(length(list.files(NAM_folder,full.names = T))==15){first24 <- c(5,6)} 
    else {print("Total NAM files for this storm not 15 or 18; skipping"); next}}

  for (k in 1:length(list.files(ST4_folder,full.names = T)[1:4])) {
    # k <-1
    ST4file <- list.files(ST4_folder,full.names = T)[k]
    ST4list[[i]][[k]] <- (raster(ST4file) %>% projectRaster(crs = "+proj=longlat +datum=WGS84"))
    ST4list[[i]][[k]] <- resample(ST4list[[i]][[k]], mask.regrid, method = "bilinear")
    
    print(min(values(ST4list[[i]][[k]]), na.rm=T))
    # values(ST4list[[i]][[k]])[which(values(ST4list[[i]][[k]]<=1))] <- 1 
    #change nonpositive projected precipitation to 0.0000000001 to implement log precip wihtout -Inf
  } 
  
  for (j in 1:length(list.files(NAM_folder,full.names = T)[first24])) {
    # j <-1
    NAMfile <- list.files(NAM_folder,full.names = T)[first24[j]]
    
    #Establish correct NAM band for total precip, mostly depends on date of storm (3 w issues)
    date_start <- str_locate_all(pattern ='_218_', NAMfile)[[1]][1,2] + 1
    storm_date <- as.numeric(substr(NAMfile,date_start,date_start+7))
    if(storm_date < 20060701){NAM_band <- 10} else 
      if(storm_date > 20060701 && storm_date < 20170101){NAM_band <- 11} else {NAM_band <- 373}
    print(NAM_band)
    NAMlist[[i]][[j]] <- (raster(NAMfile, band=NAM_band) %>% projectRaster(crs = "+proj=longlat +datum=WGS84"))
    print(min(values(NAMlist[[i]][[j]]), na.rm=T))
    # values(NAMlist[[i]][[j]])[which(values(NAMlist[[i]][[j]]<=1))] <- 1 
    #change nonpositive projected precipitation to 0.0000000001 to implement log precip without -Inf
  }
  
  first24NAM <- log((NAMlist[[i]][[1]]+NAMlist[[i]][[2]])*mask.regrid)
  values(first24NAM)[which(values(first24NAM<=0))] <- 0 #change so less than 1mm <- 0
  first24ST4 <- log((ST4list[[i]][[1]]+ST4list[[i]][[2]]+ST4list[[i]][[3]]+ST4list[[i]][[4]])*mask.regrid)
  values(first24ST4)[which(values(first24ST4<=0))] <- 0 #change so less than 1mm <- 0
  error.max <- max(abs(min(values(first24NAM-first24ST4),na.rm = T)),
                   max(values(first24NAM-first24ST4),na.rm = T))


  #######################################################################################################################################
  ST4_first12  <- ST4list[[i]][[1]]+ST4list[[i]][[2]]
  ST4_second12 <- ST4list[[i]][[3]]+ST4list[[i]][[4]]
  
  ST4_first12_logmask <- ((ST4_first12))*mask.regrid #removed log
  values(ST4_first12_logmask)[which(values(ST4_first12_logmask<=0))] <- 0 #any log precip <=0 gets changed to 0 so scale is nonnegative
  ST4_second12_logmask <- ((ST4_second12))*mask.regrid #removed log
  values(ST4_second12_logmask)[which(values(ST4_second12_logmask<=0))] <- 0 
  
  ST4_df_first12 <- rasterToPoints(ST4_first12_logmask)
  ST4_df_second12 <- rasterToPoints(ST4_second12_logmask)
  
  NAM_first12  <- NAMlist[[i]][[1]]
  NAM_second12 <- NAMlist[[i]][[2]]
  
  NAM_first12_logmask <- ((NAM_first12))*mask.regrid #removed log
  # values(NAM_first12_logmask)[which(values(NAM_first12_logmask<=0))] <- 0 #any log precip <=0 gets changed to 0 so scale is nonnegative
  NAM_second12_logmask <- ((NAM_second12))*mask.regrid #removed log
  # values(NAM_second12_logmask)[which(values(NAM_second12_logmask<=0))] <- 0 
  
  NAM_df_first12  <- rasterToPoints(NAM_first12_logmask)
  NAM_df_second12 <- rasterToPoints(NAM_second12_logmask)
  
  #The first 4 ST4 are 24 hrs. Two buffers for each 12hr group, using the 6th and 18th hour as centers (1st and 3rd files in ST4 folder)
  eye_1 <- list.files(ST4_folder,full.names = T)[1]
  eye_2 <- list.files(ST4_folder,full.names = T)[3] # add 12 hours to eye_1, aka look 2 rows down

  hurdat_file <- list.files(most.storm.folders[i], pattern = ".csv", recursive = F, full.names = T)
  hurdat <- read.csv(hurdat_file)
  colnames(hurdat) <- c("BTid", "SNum", "Year", "Month", "Day", "Hour", "Lat", "Lon", "Winds", "Pressure")
  
  time_start  <- tail(str_locate_all(pattern ='/', eye_1)[[1]],1)[,2]
  storm_time  <- substr(eye_1,time_start[1]+5,nchar(eye_1))
  storm_year  <- substr(storm_time,1,4)
  storm_month <- substr(storm_time,5,6)
  storm_day   <- substr(storm_time,7,8)
  storm_hour  <- substr(storm_time,9,10)
  
  time_start2 <- tail(str_locate_all(pattern ='/', eye_2)[[1]],1)[,2]
  storm_time2 <- substr(eye_2,time_start2[1]+5,nchar(eye_2))
  storm_year2 <- substr(storm_time2,1,4)
  storm_month2<- substr(storm_time2,5,6)
  storm_day2  <- substr(storm_time2,7,8)
  storm_hour2 <- substr(storm_time2,9,10)
  
  name_start <- tail(str_locate_all(pattern ='/', ST4_folder)[[1]],1)
  storm_name <- substr(ST4_folder,name_start[1]+5,nchar(ST4_folder))
  storm_name <- substr(ST4_folder,name_start[1]+5,nchar(ST4_folder))
  
  print(paste("Storm is", storm_name, "Year is",storm_year,"Month is",storm_month,"Day is",storm_day,"Hour is",storm_hour))
  eye1_latlon <- hurdat[hurdat$Day==as.integer(storm_day) &hurdat$Hour==as.integer(storm_hour), 7:8]
  eye2_latlon <- hurdat[hurdat$Day==as.integer(storm_day2)&hurdat$Hour==as.integer(storm_hour2),7:8]
  if(nrow(eye2_latlon)==0) eye2_latlon <- tail(hurdat,1)[,7:8]
  
  date_start <- str_locate_all(pattern ='_218_', NAMfile)[[1]][1,2] + 1
  storm_date <- as.numeric(substr(NAMfile,date_start,date_start+7))

  #######################################################################
  radius <- 700
  ST4trythis  <- ST4bufferprecip(ST4_df_first12, eye1_latlon, eye2_latlon, radius)
  ST4trythis2 <- ST4bufferprecip(ST4_df_second12, eye2_latlon, eye1_latlon, radius)
  
  NAMtrythis  <- ST4bufferprecip(NAM_df_first12, eye1_latlon, eye2_latlon, radius)
  NAMtrythis2 <- ST4bufferprecip(NAM_df_second12, eye2_latlon, eye1_latlon, radius)
  
  NAM_plotter <- log(NAMtrythis+NAMtrythis2)
  values(NAM_plotter)[which(values(NAM_plotter<=0))] <- 0 
  ST4_plotter <- log(ST4trythis+ST4trythis2)
  values(ST4_plotter)[which(values(ST4_plotter<=0))] <- 0 
  NAM_plotter <- log(NAMtrythis+NAMtrythis2)
  values(NAM_plotter)[which(values(NAM_plotter<=0))] <- 0 


  
  #Convert the three rasters to data frames for ggplot
  NAM_spdf <- as(NAM_plotter, "SpatialPixelsDataFrame")
  NAM_df <- as.data.frame(NAM_spdf)
  colnames(NAM_df) <- c("value", "x", "y")
  
  ST4_spdf <- as(ST4_plotter, "SpatialPixelsDataFrame")
  ST4_df <- as.data.frame(ST4_spdf)
  colnames(ST4_df) <- c("value", "x", "y")
  
  error <- NAM_plotter - ST4_plotter
  error_spdf <- as((error), "SpatialPixelsDataFrame")
  error_df <- as.data.frame(error_spdf)
  colnames(error_df) <- c("value", "x", "y")
  max(abs(error_df$value))
  precip.max <- max(c(ST4_df$value,NAM_df$value))
  precip.min <- min(c(ST4_df$value,NAM_df$value))

  brk=seq(-1*ceiling(error.max),ceiling(error.max),ceiling(error.max/5))
  my.limits = c(-1*ceiling(error.max),ceiling(error.max))
  plot.edge <-7.2  #this is approx the number of degrees (100km) from the storm's eye
  precipcolors <- c("#FFFFFF", "#EFFBEF", "#E0F8E0", "#BCF5A9", "#81F781",
                  "#2EFE2E", "#9AFE2E", "#C8FE2E", "#FFFF00",
                  "#FACC2E", "#FFBF00", "#FF8000", "#FF4000","#FF0000")
  regions<- c("alabama", "alaska", "arizona", "arkansas", "california", "colorado", "connecticut", "delaware",
            "district of columbia", "florida", "georgia", "hawaii", "idaho", "illinois", "indiana", "iowa",
            "kansas", "kentucky", "louisiana", "maine", "maryland", "massachusetts", "michigan", "minnesota",
            "mississippi", "missouri", "montana", "nebraska", "nevada", "new hampshire", "new jersey",
            "new mexico", "new york", "north carolina", "north dakota", "ohio", "oklahoma", "oregon",
            "pennsylvania", "rhode island", "south carolina", "south dakota", "tennessee", "texas", "utah",
            "vermont", "virginia", "washington", "west virginia", "wisconsin", "wyoming")


  g1= ggplot(aes(x=x,y=y,fill=value),data=NAM_df) + 
    geom_tile() + theme_classic() + 
    geom_polygon(data=subset(map_data("state"), region %in% regions), 
                 aes(x=long, y=lat, group=group), colour="black", fill="white", alpha=0) +
    scale_fill_gradientn(colors = precipcolors ,na.value = "white",limits=c(0,precip.max)) +
    labs(title =paste(storm_name, storm_date,"NAM"), x = "Longitude", y="Latitude") + 
    coord_fixed(xlim=c(min(eye1_latlon[2],eye2_latlon[2])-plot.edge, 
                       max(eye1_latlon[2],eye2_latlon[2])+plot.edge),
                ylim=c(min(eye1_latlon[1],eye2_latlon[1])-plot.edge, 
                       max(eye1_latlon[1],eye2_latlon[1])+plot.edge), ratio = 1)


  g2= ggplot(aes(x=x,y=y,fill=value),data=ST4_df) + 
    geom_tile() + theme_classic() + 
    geom_polygon(data=subset(map_data("state"), region %in% regions), 
                 aes(x=long, y=lat, group=group), colour="black", fill="white", alpha=0) +
    scale_fill_gradientn(colors = precipcolors ,na.value = "white",limits=c(0,precip.max)) + 
    labs(title =paste(paste(storm_name, storm_date,"ST4")),x = "Longitude", y="Latitude") + 
    coord_fixed(xlim=c(min(eye1_latlon[2],eye2_latlon[2])-plot.edge, 
                       max(eye1_latlon[2],eye2_latlon[2])+plot.edge),
                ylim=c(min(eye1_latlon[1],eye2_latlon[1])-plot.edge, 
                       max(eye1_latlon[1],eye2_latlon[1])+plot.edge), ratio = 1)

  g3= ggplot(aes(x=x,y=y,fill=value),data=error_df) + 
    geom_tile() + theme_classic() + 
    geom_polygon(data=subset(map_data("state"), region %in% regions), 
                 aes(x=long, y=lat, group=group), colour="black", fill="white", alpha=0) +
    scale_fill_gradient2(low = "blue",mid = "white", high = "red",na.value = "white") +
    labs(title =paste(paste(storm_name, storm_date,"Error: NAM - ST4")),
         x = "Longitude", y="Latitude")+
    coord_fixed(xlim=c(min(eye1_latlon[2],eye2_latlon[2])-plot.edge, 
                       max(eye1_latlon[2],eye2_latlon[2])+plot.edge),
                ylim=c(min(eye1_latlon[1],eye2_latlon[1])-plot.edge, 
                       max(eye1_latlon[1],eye2_latlon[1])+plot.edge), ratio = 1)

  multiplot(g1, g2, g3, cols=1)

}
dev.off()
```
