---
title: "GRIB Trials regridnetcdf"
author: "Stephen Walsh"
date: "10/11/2018"
output: pdf_document
---

```{r setup, include=FALSE}
library(rNOMADS)
#library(help = "rNOMADS")
library(utils)
library("ncdf4")
#install.packages("GrADS")
library(raster)
library("akima")
# install_data_package() #Need to select 1 to install data, MAPS
library(RColorBrewer) #color schemes for graphics, "RdBu" over/underestimate
library(ggplot2)
library(maps)
library(ggmap)
library(grDevices)
library("USAboundaries")
library("sf")
library(spData)
?st_geometry()
```

```{r raster_resample}
###This uses raster::resample
testnc <- nc_open("ST4.2017082606.06h-var0.nc")
testvar <- names(testnc$var)
r <- raster("ST4.2017082606.06h-var0.nc", varname=testvar)
s <- raster("nam_218_20070914_1200_f024.grb2-var40-t0.nc")
test <- resample(r, s, method='bilinear')
test2 <- resample(test, r, method='bilinear')
par(mfrow=c(1,3))
plot(r, ylim= c(25,32), xlim=c(-100,-90))
plot(test, ylim= c(25,32), xlim=c(-100,-90))
plot(test2, ylim= c(25,32), xlim=c(-100,-90))

dim(r)
dim(test)
dim(test2)
maxValue(r)
maxValue(test)
maxValue(test2)
```

## R Plots for Regridded NetCDF Files

```{r mask, echo=FALSE}
timetest_1 <- raster("/Users/stevewalsh/Downloads/test_timetest-1_hopes.nc") #flipped axes in R
timetest_15deg <- raster("/Users/stevewalsh/Downloads/test_timetest-1_15degs.nc") #flipped axes in R
mask.wgs <- raster("/Users/stevewalsh/Downloads/nws_precip_output_masks/timetestmasknearestWGS84.nc")
mask_15deg <- raster("/Users/stevewalsh/Downloads/nws_precip_output_masks/mask15degs.nc")
timetest_intmask <- raster("/Users/stevewalsh/Downloads/test_timetest-1_15intmask.nc")
garbo <- raster("/Users/stevewalsh/Downloads/garbo_15intmask.nc")
lsmask <- raster("/Users/stevewalsh/Downloads/R/Research/lsmask.nc")

new_NAM <- raster("/Volumes/LACIEHD1/NCDFtrial/meso-eta_218_2004081012bonnie/meso-eta-hi_218_20040810_1200_f060.nc")
plot(flip(flip(t(new_NAM),direction='y'),direction = "x"), xlim=c(-130,-65), ylim=c(23,50))
plot(st_geometry(spData::us_states), add=TRUE)
old_NAM <- raster("/Volumes/LACIEHD1/NAMhurtrial/meso-eta_218_2004081012bonnie/meso-eta-hi_218_20040810_1200_f060.grib",band=10)
bandnr(old_NAM)
plot(old_NAM)

plot(lsmask)
# loop_NAM <- raster("/Volumes/LACIEHD1/NAMhur/nam_218_20070815_1200_060.grb2teste.nc")
# plot(flip(flip(t(loop_NAM),direction='y'),direction = "x"))
# plot(st_geometry(spData::us_states), add=TRUE)

plot(garbo)
plot(mask.wgs)
plot(timetest_1)
plot(timetest_15deg)
plot(timetest_1*mask.wgs)

plot(flip(flip(t(timetest_1),direction='y'),direction = "x"), xlim=c(-130,-65), ylim=c(23,50))
plot(st_geometry(spData::us_states), add=TRUE)

# Load in shpae files (two ways)
s <- shapefile("/Users/stevewalsh/Downloads/R/Research/CONUS_mask_shp/CONUS_mask.shp")
plot(s)

library(rgdal)
shape <- readOGR(dsn = "/Users/stevewalsh/Downloads/R/Research/CONUS_mask_shp/", layer = "CONUS_mask")
plot(shape)

mask_precip <- mask(flip(flip(t(timetest_15deg),direction='y'),direction = "x"), s)
plot(mask_precip)
unique(values(timetest_15deg))

plot(flip(flip(t(timetest_1*mask.wgs),direction='y'),direction = "x"), xlim=c(-130,-65), ylim=c(23,50))
plot(st_geometry(spData::us_states), add=TRUE)

plot(flip(flip(t(timetest_15deg*mask_15deg),direction='y'),direction = "x"), xlim=c(-130,-65), ylim=c(23,50))
plot(st_geometry(spData::us_states), add=TRUE)

plot(flip(flip(t(timetest_1*mask.wgs),direction='y'),direction = "x"), xlim=c(-112,-90), ylim=c(25,35))
plot(st_geometry(spData::us_states), add=TRUE)
points(-97.30,29.30, pch =19)

plot(flip(flip(t(timetest_intmask*mask_15deg),direction='y'),direction = "x"), xlim=c(-112,-90), ylim=c(25,35))
plot(st_geometry(spData::us_states), add=TRUE)
points(-97.30,29.30, pch =19)
```

```{r interim mexico mask}
deg15nc <- nc_open("/Users/stevewalsh/Downloads/test_timetest-1_15degs.nc")
timetest_15deg <- raster("/Users/stevewalsh/Downloads/test_timetest-1_15degs.nc") #flipped axes in R
precip.matrix <- matrix(values(timetest_15deg), nrow = length(deg15nc$dim$lat$vals))

#deg15nc$var$precip
plot(flip(flip(t(timetest_1*mask.wgs),direction='y'),direction = "x"), xlim=c(-110,-90), ylim=c(24,35))
plot(st_geometry(spData::us_states), add=TRUE)
# timetest_15deg[1:max(which(deg15nc$dim$lon$vals < -97.5, arr.ind = T)),
#                1:max(which(deg15nc$dim$lat$vals < 26.1, arr.ind = T)),
#                1] <- 0
length(deg15nc$dim$lat$vals)*length(deg15nc$dim$lon$vals)
#unique(extract(timetest_1,1:980000)) #takes much longer


plot(timetest_15deg)
dim(ncvar_get(deg15nc))
skrt <- ncvar_get(deg15nc)
skrt[which(deg15nc$dim$lat$vals < 26.1, arr.ind = T),which(deg15nc$dim$lon$vals < -97.5, arr.ind = T)] <- 0
max(deg15nc$dim$lon$vals[deg15nc$dim$lon$vals < -97.5])

# Working on interim mask for Mexico in Python
# skrt=values(timetest_15deg)[:,st4_lat_vec<26.1][st4_lon_vec<-97.5,:]
# for i in range(1,skrt.shape[0]):
#     for j in range(1,skrt.shape[1]):
#         if np.isnan(skrt)[i,j]==False:
#             st4_data_r[:,st4_lat_vec<26.1][st4_lon_vec<-97.5,:][i,j] = 0
# skrt2=st4_data_r[:,st4_lat_vec<29.4][st4_lon_vec<-101,:]
# skrt3=st4_data_r[:,st4_lat_vec<32][st4_lon_vec<-104.72,:]

#?buffer
```

```{r buffer}
hurdat <- read.csv("/Users/stevewalsh/Downloads/R/Research/3hourlywinds/2017_08HARVEY_12UTC_0823.csv", header = F)
colnames(hurdat) <- c("BTid", "SNum", "Year", "Month", "Day", "Hour", "Lat", "Lon", "Winds", "Pressure")

radius    <- 500
centerLat <- 28.90
centerLon <- -97.30
deg15nc <- nc_open("/Users/stevewalsh/Downloads/test_timetest-1_15degs.nc")
timetest_15deg <- raster("/Users/stevewalsh/Downloads/test_timetest-1_15degs.nc") #flipped axes in R
precip.matrix <- matrix(values(timetest_15deg), nrow = length(deg15nc$dim$lat$vals))
latgrid <- matrix(rep(rev(deg15nc$dim$lat$vals),length(deg15nc$dim$lon$vals)),nrow = length(deg15nc$dim$lat$vals), byrow = F)
longrid <- matrix(rep(deg15nc$dim$lon$vals,length(deg15nc$dim$lat$vals)),nrow = length(deg15nc$dim$lat$vals), byrow = T)

# scale longtitude grid (since it's a fcn of latitude)
lonscale = cos(abs(centerLat*pi/180));
Ydist = (latgrid-centerLat)*110.54; # convert to km [i,j]
Xdist = (longrid-centerLon)*111.32*lonscale; #[i,j]
radialdist = abs(sqrt(Ydist^2+Xdist^2));
buffer_precip <- ifelse(radialdist < radius, rev(precip.matrix), NA)
plot(raster(buffer_precip), xlim = c(0.475,0.575), ylim=c(.25,.45))
# plot(st_geometry(spData::us_states), add=TRUE)
# points(-97.30,29.30, pch =19)
```



