---
title: "Plot All Storms"
author: "Steve Walsh"
date: "1/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sp)
library(raster)
library(ncdf4)
library(sf)
library(dplyr)
library(stringr) #str_locate_all "_218_" in the NAM file names 
library(rgdal)
library(colorspace)
library(ggplot2)
library(SpatialEpi) #latlong2grid()
library(geoR) #as.geodata, variog, variofit
```

Boxplots and Map Plots to Create after Running LogPrecipVariograms

```{r}
# pdf("SVG.G.48.km.old.hist.pdf")

par(mfrow=c(2,2))
summary(tau2vec);boxplot(tau2vec);hist(tau2vec)
summary(sig2vec);boxplot(sig2vec);hist(sig2vec)
summary(phivec);boxplot(phivec);hist(phivec)
summary(prRangevec);boxplot(prRangevec);hist(prRangevec)
par(mfrow=c(1,1))
# summary(kappavec);boxplot(kappavec);hist(kappavec)
pairs(cbind(tau2vec,phivec,sig2vec, prRangevec)) #,kappavec

# dev.off()
```

```{r}
# pdf("SVG.G.48.km.error.bygroups.pdf")
all_content = readLines("~/NAM-Model-Validation/csv/US_20042017_landfalls_mod.csv")
skip_second = all_content[-6]
landfalls = read.csv(textConnection(skip_second), header = T, stringsAsFactors = FALSE)
colnames(landfalls) <- c("Year","Storm","Landfall Time (UTC)","BT.Lat","BTLon","SSHWS")
landfalls$inten <- factor(ifelse(landfalls$SSHWS%in%c("TS","1","2"),"TS,1,2","3,4,5"))
landfalls$inten_alt <- factor(ifelse(landfalls$SSHWS%in%c("TS"),"TS",
                              ifelse(landfalls$SSHWS%in%c("1","2"),"1,2","3,4,5")))
landfalls$loc   <- factor(ifelse(landfalls$BT.Lat>32,"ATL",
                          ifelse(landfalls$BTLon>-88,"FL","GULF")))
landfalls$SSHWS=factor(landfalls$SSHWS, levels = levels(factor(landfalls$SSHWS))[c(5,1:4)])
landfalls$inten=factor(landfalls$inten , levels=levels(landfalls$inten)[c(2,1)])
landfalls$inten_alt=factor(landfalls$inten_alt , levels=levels(landfalls$inten_alt)[c(3,1,2)])


levels(landfalls$SSHWS)
stormsTS<- which(landfalls$SSHWS=="TS")
storms1 <- which(landfalls$SSHWS==1)
storms2 <- which(landfalls$SSHWS==2)
storms3 <- which(landfalls$SSHWS==3)
storms4 <- which(landfalls$SSHWS==4)
storms5 <- which(landfalls$SSHWS==5)
storms_TS_1_2 <- c(stormsTS,storms1,storms2)
storms_3_4_5  <- c(storms3,storms4,storms5)

stormsATL <- which(landfalls$BT.Lat>32)
stormsFL  <- which(landfalls$BT.Lat<32&landfalls$BTLon> -88)
stormsGULF<- which(landfalls$BT.Lat<32&landfalls$BTLon< -88)
dim(landfalls[stormsATL,]);dim(landfalls[stormsFL,]);dim(landfalls[stormsGULF,])

plot(landfalls[,5:4], main="Plot by Location")
points(landfalls[stormsATL,5:4],col="red", pch=16)
points(landfalls[stormsFL,5:4],col="blue", pch=16)
points(landfalls[stormsGULF,5:4],col="green", pch=16)
legend("topleft", inset=.02, title="Storm Location",
   c("ATL","FL","GULF"), fill=c("red","blue","green"), horiz=TRUE, cex=1)
fields::US(col="gray80", add=T)


# par(cex.axis=2, cex.lab=2, cex.main=3.5)  #for poster sized semivariogram
# plot(simul.modvar,main=paste0("SVG for ", storm_year," ",storm_name), #settings for poster png
#    ylim=c(0,1),cex=4,pch=19);lines(sim.mod.cressie.nug,col="red",lwd=4) #poster size


g_byloc <- ggplot() + 
  geom_tile() + theme_classic() + 
  geom_polygon(data=subset(map_data("state"), region %in% regions), 
               aes(x=long, y=lat, group=group), colour="black", fill="white", alpha=0) +
  geom_point(data = landfalls[stormsATL,], aes(x=BTLon, y = BT.Lat, color="ATL"))+#,size=80))+ ##for poster
  geom_point(data = landfalls[stormsFL,], aes(x=BTLon, y = BT.Lat, color="FL"))+#,size=80))+ ##for poster
  geom_point(data = landfalls[stormsGULF,], aes(x=BTLon, y = BT.Lat, color="GULF"))+#,size=80))+ ##for poster
  labs(title ="Landfalls by Location", x = "Longitude", y="Latitude") + 
  # theme(plot.title = element_text(size=36),axis.text =  element_text(size = 26), #use these for poster
  #      axis.title =  element_text(size = 26))+ #use these for poster plots
  coord_fixed(xlim=c(-100, -68), ylim = c(24,45), ratio = 1)+
  scale_colour_manual(name="Location", values = c("green","blue","red"))

g_byloc

g_byint <- ggplot() + 
  geom_tile() + theme_classic() + 
  geom_polygon(data=subset(map_data("state"), region %in% regions), 
               aes(x=long, y=lat, group=group), colour="black", fill="white", alpha=0) +
  geom_point(data = landfalls[c(stormsTS),], aes(x=BTLon, y = BT.Lat, color=" TS"))+
  geom_point(data = landfalls[c(storms1,storms2),], aes(x=BTLon, y = BT.Lat, color="1/2"))+
  geom_point(data = landfalls[c(storms3,storms4,storms5),], aes(x=BTLon, y = BT.Lat, color="3/4/5"))+
  labs(title ="Landfalls by Intensity", x = "Longitude", y="Latitude") + 
  coord_fixed(xlim=c(-100, -68), ylim = c(24,45), ratio = 1)+
  scale_colour_manual(name="Intensity", values = c("green","blue","red"))

g_byint

# plot(landfalls[,5:4], main="Plot by Intensity")
# points(landfalls[storms_TS_1_2,5:4],col="green")
# points(landfalls[storms2,5:4], col="blue" )
# points(landfalls[storms_3_4_5 ,5:4],col="red")
# legend("topleft", inset=.02, title="Storm Intensity",
#    c("TS,1","2","3,4,5"), fill=c("green","blue","red"), horiz=TRUE, cex=1)


par(mfrow=c(2,2))
boxplot(phivec~inten, data=landfalls, ylab= expression(phi), 
        main=expression(paste(phi, " by intensity")))
boxplot(prRangevec~inten, data=landfalls, ylab="Prac Rg by intensity",
        main=expression("Practical Range by intensity"))
boxplot(tau2vec~inten, data=landfalls, ylab= expression(tau^2), 
        main=expression(paste(tau^2, " by intensity")))
boxplot(sig2vec~inten, data=landfalls, ylab= expression(sigma^2), 
        main=expression(paste(sigma^2, " by intensity")))

par(mfrow=c(2,2))
boxplot(phivec~inten_alt, data=landfalls, ylab= expression(phi), 
        main=expression(paste(phi, " by intensity")))
boxplot(prRangevec~inten_alt, data=landfalls, ylab="Prac Rg by intensity",
        main=expression("Practical Range by intensity"))
boxplot(tau2vec~inten_alt, data=landfalls, ylab= expression(tau^2), 
        main=expression(paste(tau^2, " by intensity")))
boxplot(sig2vec~inten_alt, data=landfalls, ylab= expression(sigma^2), 
        main=expression(paste(sigma^2, " by intensity")))


par(mfrow=c(2,2))
boxplot(phivec~SSHWS, data=landfalls, ylab= expression(phi), 
        main=expression(paste(phi, " by intensity")))
boxplot(prRangevec~SSHWS, data=landfalls, ylab="Prac Rg by intensity",
        main=expression("Practical Range by intensity"))
boxplot(tau2vec~SSHWS, data=landfalls, ylab= expression(tau^2), 
        main=expression(paste(tau^2, " by intensity")))
boxplot(sig2vec~SSHWS, data=landfalls, ylab= expression(sigma^2), 
        main=expression(paste(sigma^2, " by intensity")))



par(mfrow=c(2,2))
boxplot(phivec~loc, data=landfalls, ylab= expression(phi), 
        main=expression(paste(phi, " by location")))
boxplot(prRangevec~loc, data=landfalls, ylab="Prac Rg by location",
        main=expression("Practical Range by location"))
boxplot(tau2vec~loc, data=landfalls, ylab= expression(tau^2), 
        main=expression(paste(tau^2, " by location")))
boxplot(sig2vec~loc, data=landfalls, ylab= expression(sigma^2), 
        main=expression(paste(sigma^2, " by location")))

pairs(cbind(phivec,prRangevec,tau2vec,sig2vec)) #,kappavec

par(mfrow=c(2,2))
plot(phivec, type="l", main=expression(paste(phi, " over time")))
plot(prRangevec, type="l", main="Practical range over time")
plot(tau2vec, type="l", main=expression(paste(tau^2, " over time")))
plot(sig2vec, type="l", main=expression(paste(sigma^2, " over time")))

# dev.off()
```

```{r}
# pdf("SVGskrt.pdf")
dim(landfalls[stormsTS,]);dim(landfalls[storms1,]);
dim(landfalls[storms2,]);dim(landfalls[storms3,]);
dim(landfalls[storms4,]);dim(landfalls[storms5,])

stormsATL <- which(landfalls$BT.Lat>32)
stormsFL  <- which(landfalls$BT.Lat<32&landfalls$BTLon> -88)
stormsGULF<- which(landfalls$BT.Lat<32&landfalls$BTLon< -88)
dim(landfalls[stormsATL,]);dim(landfalls[stormsFL,]);dim(landfalls[stormsGULF,])

plot(landfalls[,5:4], main="Plot by Location")
points(landfalls[stormsATL,5:4],col="red")
points(landfalls[stormsFL,5:4],col="blue")
points(landfalls[stormsGULF,5:4],col="green")

storms_TS_1_2 <- c(stormsTS,storms1,storms2)
storms_3_4_5  <- c(storms3,storms4,storms5)


plot(landfalls[,5:4], main="Plot by Intensity")
points(landfalls[storms_TS_1_2,5:4],col="green")
points(landfalls[storms_3_4_5 ,5:4],col="red")





par(mfrow=c(2,2))
summary(tau2vec[stormsATL]);boxplot(tau2vec[stormsATL]);hist(tau2vec[stormsATL])
summary(sig2vec[stormsATL]);boxplot(sig2vec[stormsATL]);hist(sig2vec[stormsATL])
summary(phivec[stormsATL]);boxplot(phivec[stormsATL]);hist(phivec[stormsATL])
summary(prRangevec[stormsATL]);boxplot(prRangevec[stormsATL]);hist(prRangevec[stormsATL])
# par(mfrow=c(1,2))
# summary(kappavec[stormsATL]);boxplot(kappavec[stormsATL]);hist(kappavec[stormsATL])
par(mfrow=c(1,1))
pairs(cbind(tau2vec[stormsATL],phivec[stormsATL],sig2vec[stormsATL], prRangevec[stormsATL])) #,kappavec[stormsATL]


par(mfrow=c(2,2))
summary(tau2vec[stormsFL]);boxplot(tau2vec[stormsFL], main="FL");hist(tau2vec[stormsFL], main="FL")
summary(sig2vec[stormsFL]);boxplot(sig2vec[stormsFL], main="FL");hist(sig2vec[stormsFL], main="FL")
summary(phivec[stormsFL]) ;boxplot(phivec[stormsFL] , main="FL");hist(phivec[stormsFL] , main="FL")
summary(prRangevec[stormsFL]);boxplot(prRangevec[stormsFL],main="FL");hist(prRangevec[stormsFL],main="FL")
# par(mfrow=c(1,2))
# summary(kappavec[stormsFL]);boxplot(kappavec[stormsFL]);hist(kappavec[stormsFL])
par(mfrow=c(1,1))
pairs(cbind(tau2vec[stormsFL],phivec[stormsFL],sig2vec[stormsFL], prRangevec[stormsFL])) #,kappavec[stormsFL]



par(mfrow=c(2,2))
summary(tau2vec[stormsGULF]);boxplot(tau2vec[stormsGULF], main="GULF");hist(tau2vec[stormsGULF], main="GULF")
summary(sig2vec[stormsGULF]);boxplot(sig2vec[stormsGULF], main="GULF");hist(sig2vec[stormsGULF], main="GULF")
summary(phivec[stormsGULF]) ;boxplot(phivec[stormsGULF] , main="GULF");hist(phivec[stormsGULF] , main="GULF")
summary(prRangevec[stormsGULF]);boxplot(prRangevec[stormsGULF],main="GULF");hist(prRangevec[stormsGULF],main="GULF")
# par(mfrow=c(1,2))
# summary(kappavec[stormsGULF]);boxplot(kappavec[stormsGULF]);hist(kappavec[stormsGULF])
par(mfrow=c(1,1))
pairs(cbind(tau2vec[stormsGULF],phivec[stormsGULF],sig2vec[stormsGULF], prRangevec[stormsGULF])) #,kappavec[stormsGULF]


par(mfrow=c(2,2))
summary(tau2vec[storms_TS_1_2]);boxplot(tau2vec[storms_TS_1_2], main="_TS_1_2");hist(tau2vec[storms_TS_1_2], main="_TS_1_2")
summary(sig2vec[storms_TS_1_2]);boxplot(sig2vec[storms_TS_1_2], main="_TS_1_2");hist(sig2vec[storms_TS_1_2], main="_TS_1_2")
summary(phivec[storms_TS_1_2]) ;boxplot(phivec[storms_TS_1_2] , main="_TS_1_2");hist(phivec[storms_TS_1_2] , main="_TS_1_2")
summary(prRangevec[storms_TS_1_2]);boxplot(prRangevec[storms_TS_1_2],main="_TS_1_2");hist(prRangevec[storms_TS_1_2],main="_TS_1_2")
# par(mfrow=c(1,2))
# summary(kappavec[storms_TS_1_2]);boxplot(kappavec[storms_TS_1_2]);hist(kappavec[storms_TS_1_2])
par(mfrow=c(1,1))
pairs(cbind(tau2vec[storms_TS_1_2],phivec[storms_TS_1_2],sig2vec[storms_TS_1_2], prRangevec[storms_TS_1_2])) #,kappavec[storms_TS_1_2]


par(mfrow=c(2,2))
summary(tau2vec[storms_3_4_5]);boxplot(tau2vec[storms_3_4_5], main="_3_4_5");hist(tau2vec[storms_3_4_5], main="_3_4_5")
summary(sig2vec[storms_3_4_5]);boxplot(sig2vec[storms_3_4_5], main="_3_4_5");hist(sig2vec[storms_3_4_5], main="_3_4_5")
summary(phivec[storms_3_4_5]) ;boxplot(phivec[storms_3_4_5] , main="_3_4_5");hist(phivec[storms_3_4_5] , main="_3_4_5")
summary(prRangevec[storms_3_4_5]);boxplot(prRangevec[storms_3_4_5],main="_3_4_5");hist(prRangevec[storms_3_4_5],main="_3_4_5")
# par(mfrow=c(1,2))
# summary(kappavec[storms_3_4_5]);boxplot(kappavec[storms_3_4_5]);hist(kappavec[storms_3_4_5])
par(mfrow=c(1,1))
pairs(cbind(tau2vec[storms_3_4_5],phivec[storms_3_4_5],sig2vec[storms_3_4_5], prRangevec[storms_3_4_5])) #,kappavec[storms_3_4_5]



# dev.off()
```

```{r}
# pdf("SVG.G.48.km.old.byplottype.pdf")

par(mfrow=c(1,3))
boxplot(tau2vec,by=landfalls$SSHWS)
boxplot(tau2vec[stormsFL])
boxplot(tau2vec[stormsGULF])

summary(tau2vec[stormsATL]);hist(tau2vec[stormsATL])
summary(sig2vec[stormsATL]);boxplot(sig2vec[stormsATL]);hist(sig2vec[stormsATL])
summary(phivec[stormsATL]);boxplot(phivec[stormsATL]);hist(phivec[stormsATL])
summary(prRangevec[stormsATL]);boxplot(prRangevec[stormsATL]);hist(prRangevec[stormsATL])
# par(mfrow=c(1,2))
# summary(kappavec[stormsATL]);boxplot(kappavec[stormsATL]);hist(kappavec[stormsATL])
par(mfrow=c(1,1))
pairs(cbind(tau2vec[stormsATL],phivec[stormsATL],sig2vec[stormsATL], prRangevec[stormsATL])) #,kappavec[stormsATL]


par(mfrow=c(2,2))
summary(tau2vec[stormsFL]);boxplot(tau2vec[stormsFL], main="FL");hist(tau2vec[stormsFL], main="FL")
summary(sig2vec[stormsFL]);boxplot(sig2vec[stormsFL], main="FL");hist(sig2vec[stormsFL], main="FL")
summary(phivec[stormsFL]) ;boxplot(phivec[stormsFL] , main="FL");hist(phivec[stormsFL] , main="FL")
summary(prRangevec[stormsFL]);boxplot(prRangevec[stormsFL],main="FL");hist(prRangevec[stormsFL],main="FL")
# par(mfrow=c(1,2))
# summary(kappavec[stormsFL]);boxplot(kappavec[stormsFL]);hist(kappavec[stormsFL])
par(mfrow=c(1,1))
pairs(cbind(tau2vec[stormsFL],phivec[stormsFL],sig2vec[stormsFL], prRangevec[stormsFL])) #,kappavec[stormsFL]



par(mfrow=c(2,2))
summary(tau2vec[stormsGULF]);boxplot(tau2vec[stormsGULF], main="GULF");hist(tau2vec[stormsGULF], main="GULF")
summary(sig2vec[stormsGULF]);boxplot(sig2vec[stormsGULF], main="GULF");hist(sig2vec[stormsGULF], main="GULF")
summary(phivec[stormsGULF]) ;boxplot(phivec[stormsGULF] , main="GULF");hist(phivec[stormsGULF] , main="GULF")
summary(prRangevec[stormsGULF]);boxplot(prRangevec[stormsGULF],main="GULF");hist(prRangevec[stormsGULF],main="GULF")
# par(mfrow=c(1,2))
# summary(kappavec[stormsGULF]);boxplot(kappavec[stormsGULF]);hist(kappavec[stormsGULF])
par(mfrow=c(1,1))
pairs(cbind(tau2vec[stormsGULF],phivec[stormsGULF],sig2vec[stormsGULF], prRangevec[stormsGULF])) #,kappavec[stormsGULF]


par(mfrow=c(2,2))
summary(tau2vec[storms_TS_1_2]);boxplot(tau2vec[storms_TS_1_2], main="_TS_1_2");hist(tau2vec[storms_TS_1_2], main="_TS_1_2")
summary(sig2vec[storms_TS_1_2]);boxplot(sig2vec[storms_TS_1_2], main="_TS_1_2");hist(sig2vec[storms_TS_1_2], main="_TS_1_2")
summary(phivec[storms_TS_1_2]) ;boxplot(phivec[storms_TS_1_2] , main="_TS_1_2");hist(phivec[storms_TS_1_2] , main="_TS_1_2")
summary(prRangevec[storms_TS_1_2]);boxplot(prRangevec[storms_TS_1_2],main="_TS_1_2");hist(prRangevec[storms_TS_1_2],main="_TS_1_2")
# par(mfrow=c(1,2))
# summary(kappavec[storms_TS_1_2]);boxplot(kappavec[storms_TS_1_2]);hist(kappavec[storms_TS_1_2])
par(mfrow=c(1,1))
pairs(cbind(tau2vec[storms_TS_1_2],phivec[storms_TS_1_2],sig2vec[storms_TS_1_2], prRangevec[storms_TS_1_2])) #,kappavec[storms_TS_1_2]


par(mfrow=c(2,2))
summary(tau2vec[storms_3_4_5]);boxplot(tau2vec[storms_3_4_5], main="_3_4_5");hist(tau2vec[storms_3_4_5], main="_3_4_5")
summary(sig2vec[storms_3_4_5]);boxplot(sig2vec[storms_3_4_5], main="_3_4_5");hist(sig2vec[storms_3_4_5], main="_3_4_5")
summary(phivec[storms_3_4_5]) ;boxplot(phivec[storms_3_4_5] , main="_3_4_5");hist(phivec[storms_3_4_5] , main="_3_4_5")
summary(prRangevec[storms_3_4_5]);boxplot(prRangevec[storms_3_4_5],main="_3_4_5");hist(prRangevec[storms_3_4_5],main="_3_4_5")
# par(mfrow=c(1,2))
# summary(kappavec[storms_3_4_5]);boxplot(kappavec[storms_3_4_5]);hist(kappavec[storms_3_4_5])
par(mfrow=c(1,1))
pairs(cbind(tau2vec[storms_3_4_5],phivec[storms_3_4_5],sig2vec[storms_3_4_5], prRangevec[storms_3_4_5])) #,kappavec[storms_3_4_5]

# dev.off()
```
